import { colors } from './theme';
import type { FamilyMember, Recipe, RecipeStep } from './types';

export const familyMembers: FamilyMember[] = [
  { initials: 'F', name: 'Fatima', color: colors.sagePale, ink: colors.forest },
  { initials: 'M', name: 'Mariam', color: colors.clayPale, ink: colors.clay },
  { initials: 'S', name: 'Saeed', color: '#EEE0AD', ink: '#806522' },
  { initials: '+', name: 'Invite', color: '#D9DCED', ink: '#525A8D' },
];

export const recipes: Recipe[] = [
  {
    id: 'luqaimat',
    name: 'Luqaimat',
    arabicName: 'لقيمات',
    keeper: 'Grandma Fatima',
    year: '1987',
    category: 'Sweets',
    summary: 'Golden dumplings with date syrup, preserved in Grandma Fatima’s own voice.',
    duration: '6:42',
    checkpointCount: 5,
    storyCount: 3,
    confidence: 86,
    accent: '#D9B68E',
    accentDeep: '#B96534',
    art: 'dumplings',
    quote: 'My mother always made the first batch small. She said the oil also needs to learn.',
    quoteStep: 'Memory attached to Step 4',
    knowledge: [
      { label: 'TEXTURE', title: 'The ribbon test', detail: 'The dough folds back into itself in roughly three seconds.' },
      { label: 'SOUND', title: 'Listen for the softer sizzle', detail: 'Grandma lowers the heat when the oil changes from a sharp crackle.' },
    ],
    lesson: {
      title: 'Mastering the dough',
      steps: [
        { title: 'Bring the dough together', checkpoint: 'Mix until no dry flour remains and the dough looks evenly saffron-gold.', coach: 'Sweep around the bowl once more; a small dry pocket is still visible at the edge.', familyTip: 'Grandma Fatima mixes with an open hand so she can feel every dry patch.' },
        { title: 'Let it wake up', checkpoint: 'The rested dough should look softly domed with tiny bubbles across the surface.', coach: 'The bubbles are still sparse. Give the covered bowl a little more time in a warm place.', familyTip: 'She listens for a faint airy sound when the cover is lifted.' },
        { title: 'Find the ribbon', checkpoint: 'Let the dough fall from your fingers in one slow, unbroken ribbon.', coach: 'Your mixture may be slightly thick. Add one teaspoon of warm water, then compare again.', familyTip: 'Count slowly to three—the ribbon should fold back into itself before disappearing.' },
        { title: 'Read the oil', checkpoint: 'A tiny test drop should rise steadily, surrounded by gentle bubbles.', coach: 'The test drop is colouring too quickly. Lower the heat and wait before the first batch.', familyTip: 'The first small piece teaches the oil; it is never part of the serving plate.' },
        { title: 'Finish at deep gold', checkpoint: 'Turn each piece when its lower edge becomes amber, then lift at an even deep gold.', coach: 'One side is ready. Turn gently now and watch for the sizzle to soften.', familyTip: 'Grandma Fatima judges the final moment by sound as much as colour.' },
      ],
    },
  },
  {
    id: 'harees',
    name: 'Harees',
    arabicName: 'هريس',
    keeper: 'Grandma Fatima',
    year: '1992',
    category: 'Mains',
    summary: 'A patient wheat and chicken dish remembered by its texture, rhythm and quiet simmer.',
    duration: '9:18',
    checkpointCount: 4,
    storyCount: 2,
    confidence: 91,
    accent: '#C8B997',
    accentDeep: '#8C6842',
    art: 'grain',
    quote: 'Do not rush the wooden spoon. The wheat tells you when it is ready to become one.',
    quoteStep: 'Grandma’s phrase from Step 3',
    knowledge: [
      { label: 'RHYTHM', title: 'The slow fold', detail: 'Fold from the edge to the centre until the mixture moves as a single soft wave.' },
      { label: 'TEXTURE', title: 'A trail that closes', detail: 'The spoon leaves a line for a moment, then the harees gently settles over it.' },
    ],
    lesson: {
      title: 'Finding the final texture',
      steps: [
        { title: 'Check the soaked wheat', checkpoint: 'Each grain should look swollen and give easily when pressed between two fingers.', coach: 'The centre still looks firm. Let the wheat soak a little longer before cooking.', familyTip: 'Grandma Fatima presses one grain against the side of the bowl instead of watching the clock.' },
        { title: 'Cook until the fibres loosen', checkpoint: 'The chicken should separate with the back of the spoon without pulling.', coach: 'The fibres are still holding together. Keep the simmer low and patient.', familyTip: 'A quiet pot gives a softer harees; hard boiling makes the texture uneven.' },
        { title: 'Fold everything into one', checkpoint: 'Wheat and chicken should stop looking separate as you fold from edge to centre.', coach: 'A few fibres are still distinct. Continue the same slow folding rhythm.', familyTip: 'She turns the pot a little after every few folds so no edge is forgotten.' },
        { title: 'Find the closing trail', checkpoint: 'The spoon trail should stay visible for a moment, then close slowly behind you.', coach: 'The mixture still looks slightly loose. Continue folding gently before adding any more water.', familyTip: 'This is the moment Grandma calls “one soft wave.”' },
        { title: 'Finish with a soft shine', checkpoint: 'The surface should settle smooth while a small spoon of ghee remains visible on top.', coach: 'The surface is almost there. Smooth it once without beating out the softness.', familyTip: 'The final spoon circles only once—harees should arrive calm at the table.' },
      ],
    },
  },
  {
    id: 'machboos',
    name: 'Chicken Machboos',
    arabicName: 'مجبوس دجاج',
    keeper: 'Aunt Mariam',
    year: '2001',
    category: 'Mains',
    summary: 'Fragrant spiced rice with chicken, dried lime and Aunt Mariam’s steam test.',
    duration: '8:05',
    checkpointCount: 6,
    storyCount: 4,
    confidence: 82,
    accent: '#D8A85F',
    accentDeep: '#8B4D2B',
    art: 'rice',
    quote: 'When the steam smells round instead of sharp, the rice has taken in the whole story.',
    quoteStep: 'Aunt Mariam’s note from Step 5',
    knowledge: [
      { label: 'AROMA', title: 'Wait for the spices to soften', detail: 'The sharp dried-lime scent becomes warmer just before the rice is covered.' },
      { label: 'STEAM', title: 'The cloth test', detail: 'Aunt Mariam checks that the steam rises evenly before lowering the heat.' },
    ],
    lesson: {
      title: 'Reading the rice',
      steps: [
        { title: 'Bloom the spice base', checkpoint: 'The spice aroma should become warm and rounded rather than sharp.', coach: 'The scent is still sharp. Stir gently and give the spices another moment.', familyTip: 'Aunt Mariam smells above the pot before adding anything else.' },
        { title: 'Build colour on the chicken', checkpoint: 'The chicken should release easily from the pot with a light golden surface.', coach: 'One side still looks pale. Leave it undisturbed briefly before turning.', familyTip: 'She waits for the pot to release the chicken; pulling early leaves the flavour behind.' },
        { title: 'Settle the rice evenly', checkpoint: 'The rice should form an even layer beneath liquid that just covers the grains.', coach: 'The centre is slightly higher. Level it gently without compacting the rice.', familyTip: 'Aunt Mariam shakes the pot by its handles instead of pressing with a spoon.' },
        { title: 'Watch the steam paths', checkpoint: 'Small steam holes should appear across the surface, including near the centre.', coach: 'Steam is gathering mostly at the edge. Keep the lid closed and the heat low.', familyTip: 'Uneven steam means the rice needs time, not stirring.' },
        { title: 'Rest before fluffing', checkpoint: 'Look for separate grains with soft, glossy centres and no wet layer below.', coach: 'The grains are close. Rest the pot covered for three more minutes before fluffing from the sides.', familyTip: 'She fluffs from the outside inward so the long grains stay whole.' },
      ],
    },
  },
  {
    id: 'khameer',
    name: 'Khameer Bread',
    arabicName: 'خبز خمير',
    keeper: 'Mama Aisha',
    year: '1998',
    category: 'Bread',
    summary: 'Soft saffron bread captured through hand feel, surface bubbles and the family breakfast story.',
    duration: '7:26',
    checkpointCount: 5,
    storyCount: 3,
    confidence: 88,
    accent: '#DEA36B',
    accentDeep: '#A75C35',
    art: 'bread',
    quote: 'The dough should feel like your palm after you have warmed it around a tea cup.',
    quoteStep: 'Mama Aisha’s comparison from Step 2',
    knowledge: [
      { label: 'TOUCH', title: 'A warm-palm softness', detail: 'The dough keeps a shallow fingertip mark without sticking to the whole finger.' },
      { label: 'VISUAL', title: 'Watch the small bubbles', detail: 'Turn the bread when bubbles reach the centre rather than judging only by colour.' },
    ],
    lesson: {
      title: 'Knowing when to turn',
      steps: [
        { title: 'Wake the yeast', checkpoint: 'A creamy foam should gather across the surface with a gently sweet smell.', coach: 'Only the edges are active. Give the mixture a few more warm minutes.', familyTip: 'Mama Aisha looks for foam that holds for a moment when the bowl moves.' },
        { title: 'Feel the dough', checkpoint: 'A fingertip should leave a shallow mark without the dough coating your whole finger.', coach: 'The dough is still a little firm. Wet your hand lightly and fold again.', familyTip: 'It should feel like your palm after warming it around a tea cup.' },
        { title: 'Wait for the rounded rise', checkpoint: 'The dough should look airy and rounded, with its earlier fingertip mark gone.', coach: 'The surface is relaxing but not yet airy. Keep it covered a little longer.', familyTip: 'She protects the bowl from direct air, even on a warm morning.' },
        { title: 'Read the first side', checkpoint: 'Wait until small bubbles travel from the edge to the centre.', coach: 'The centre needs a little longer. Keep the heat steady and watch for two or three new bubbles.', familyTip: 'The centre bubbles matter more than the colour at the edge.' },
        { title: 'Finish with honey-coloured spots', checkpoint: 'The second side should show soft golden patches while the bread still bends easily.', coach: 'The colour is ready. Lift it now before the centre loses its softness.', familyTip: 'Mama Aisha stacks the breads under cloth so their steam keeps them tender.' },
      ],
    },
  },
  {
    id: 'balaleet',
    name: 'Balaleet',
    arabicName: 'بلاليط',
    keeper: 'Uncle Saeed',
    year: '2004',
    category: 'Breakfast',
    summary: 'Sweet saffron vermicelli with egg, remembered through balance rather than exact spoonfuls.',
    duration: '5:51',
    checkpointCount: 4,
    storyCount: 2,
    confidence: 79,
    accent: '#E5C36E',
    accentDeep: '#9A7428',
    art: 'noodles',
    quote: 'Taste after the egg goes on top—the sweet and savoury should arrive together.',
    quoteStep: 'Uncle Saeed’s tasting note',
    knowledge: [
      { label: 'BALANCE', title: 'Sweet meets savoury', detail: 'The saffron sweetness should remain gentle enough for the seasoned egg to be noticed.' },
      { label: 'TEXTURE', title: 'Keep the threads separate', detail: 'Lift from underneath instead of stirring in circles so the vermicelli stays light.' },
    ],
    lesson: {
      title: 'Balancing the final plate',
      steps: [
        { title: 'Soften without breaking', checkpoint: 'A vermicelli strand should bend easily while keeping a slight bite at the centre.', coach: 'The strand still snaps when bent. Give it a brief moment longer in the water.', familyTip: 'Uncle Saeed tastes one strand early because it keeps cooking after draining.' },
        { title: 'Keep the threads separate', checkpoint: 'The drained vermicelli should fall in loose threads rather than one heavy bundle.', coach: 'The strands are gathering together. Lift and separate them gently from underneath.', familyTip: 'Never stir in circles—lift from the bottom and let the threads fall.' },
        { title: 'Fold in the saffron sweetness', checkpoint: 'The colour and gloss should be even, with no syrup collecting at the bottom.', coach: 'A small dark patch remains. Fold once more from that side of the pan.', familyTip: 'He stops folding as soon as the colour is even so the threads stay long.' },
        { title: 'Set the egg softly', checkpoint: 'The egg should be just set and flexible enough to drape over the vermicelli.', coach: 'The surface is still glossy in the centre. Give it one quiet minute.', familyTip: 'The egg continues setting on the warm noodles, so he removes it early.' },
        { title: 'Taste both together', checkpoint: 'The vermicelli threads should lift apart, with sweet saffron and savoury egg in one bite.', coach: 'The strands look slightly tight. Fold in one spoon of reserved cooking water before plating.', familyTip: 'Uncle Saeed never adjusts the sweetness until he tastes it with the egg.' },
      ],
    },
  },
];

export const featuredRecipe: Recipe = recipes[0]!;

export const extractedSteps: RecipeStep[] = [
  {
    index: 'Step 1',
    title: 'Mix the dough',
    detail: 'Flour, yeast, saffron and warm water were combined by hand.',
    insight: 'Visual checkpoint',
  },
  {
    index: 'Step 2',
    title: 'Wait for the ribbon',
    detail: 'The dough should fall slowly from the fingers without breaking.',
    insight: "Grandma's phrase",
  },
  {
    index: 'Step 3',
    title: 'Fry until deep gold',
    detail: 'Turn each piece once the lower edge becomes amber.',
    insight: 'Visual checkpoint',
  },
];
